services:

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"

  auth-service:
    build:
      context: ./backend
      dockerfile: auth-service/dockerfile
    container_name: auth-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce-auth

  catalog-service:
    build:
      context: ./backend
      dockerfile: catalog-service/dockerfile
    container_name: catalog-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce-catalog

  order-service:
    build:
      context: ./backend
      dockerfile: order-service/dockerfile
    container_name: order-service
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce-order

  payment-service:
    build:
      context: ./backend
      dockerfile: payment-service/dockerfile
    container_name: payment-service
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce-payment

  review-service:
    build:
      context: ./backend
      dockerfile: review-service/dockerfile
    container_name: review-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce-review

  notification-service:
    build:
      context: ./backend
      dockerfile: notification-service/dockerfile
    container_name: notification-service
    depends_on:
      - rabbitmq

  api-gateway:
    build:
      context: ./backend
      dockerfile: api-gateway/dockerfile
    container_name: api-gateway
    depends_on:
      - auth-service
      - catalog-service
      - order-service
      - payment-service
      - review-service
    ports:
      - "3000:3000"

volumes:
  postgres_data:
