services:

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"

  auth-service:
    build:
      context: ./backend
      dockerfile: auth-service/dockerfile
    container_name: auth-service
    depends_on:
      - postgres
    volumes:
      - ./backend/auth-service:/app
      - ./backend/proto:/app/proto
      - auth_node_modules:/app/node_modules
    command: npm run start:dev
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce-auth
      CHOKIDAR_USEPOLLING: "true"

  catalog-service:
    build:
      context: ./backend
      dockerfile: catalog-service/dockerfile
    container_name: catalog-service
    depends_on:
      - postgres
    volumes:
      - ./backend/catalog-service:/app
      - ./backend/proto:/app/proto
      - catalog_node_modules:/app/node_modules
    command: npm run start:dev
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce-catalog
      CHOKIDAR_USEPOLLING: "true"

  order-service:
    build:
      context: ./backend
      dockerfile: order-service/dockerfile
    container_name: order-service
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./backend/order-service:/app
      - ./backend/proto:/app/proto
      - order_node_modules:/app/node_modules
    command: npm run start:dev
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce-order
      CHOKIDAR_USEPOLLING: "true"

  payment-service:
    build:
      context: ./backend
      dockerfile: payment-service/dockerfile
    container_name: payment-service
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./backend/payment-service:/app
      - ./backend/proto:/app/proto
      - payment_node_modules:/app/node_modules
    command: npm run start:dev
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce-payment
      CHOKIDAR_USEPOLLING: "true"

  review-service:
    build:
      context: ./backend
      dockerfile: review-service/dockerfile
    container_name: review-service
    depends_on:
      - postgres
    volumes:
      - ./backend/review-service:/app
      - ./backend/proto:/app/proto
      - review_node_modules:/app/node_modules
    command: npm run start:dev
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce-review
      CHOKIDAR_USEPOLLING: "true"

  notification-service:
    build:
      context: ./backend
      dockerfile: notification-service/dockerfile
    container_name: notification-service
    depends_on:
      - rabbitmq
    volumes:
      - ./backend/notification-service:/app
      - notification_node_modules:/app/node_modules
    command: npm run start:dev
    environment:
      CHOKIDAR_USEPOLLING: "true"

  api-gateway:
    build:
      context: ./backend
      dockerfile: api-gateway/dockerfile
    container_name: api-gateway
    depends_on:
      - auth-service
      - catalog-service
      - order-service
      - payment-service
      - review-service
    ports:
      - "3000:3000"
    volumes:
      - ./backend/api-gateway:/app
      - ./backend/proto:/app/proto
      - gateway_node_modules:/app/node_modules
    command: npm run start:dev
    environment:
      CHOKIDAR_USEPOLLING: "true"

volumes:
  postgres_data:
  auth_node_modules:
  catalog_node_modules:
  order_node_modules:
  payment_node_modules:
  review_node_modules:
  notification_node_modules:
  gateway_node_modules:
