// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import Link from "next/link";
// import { Toaster } from "sonner";
// import { LogoutComponent } from "../user/components/auth_components/logoutComponent";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function Layout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         <Toaster position="top-center" richColors></Toaster>
//         <div>
//           <nav className="flex items-center gap-4 p-4 bg-sky-900 text-white text-xl text-shadow-xl shadow-xl font-serif font-bold">
//             <Link href="/" className=" active:text-amber-200">
//               Home
//             </Link>
//             <Link href="/admin/login" className=" active:text-amber-200">
//               Login
//             </Link>
//             <Link href="/admin/category" className=" active:text-amber-200">
//               Categories
//             </Link>
//             <Link href="/admin/orders" className=" active:text-amber-200">
//               Orders
//             </Link>
//             <Link href="/admin/payments" className=" active:text-amber-200">
//               Payments
//             </Link>
//             <Link href="/admin/products" className=" active:text-amber-200">
//               Products
//             </Link>
//             <span className="ml-auto">
//               <LogoutComponent></LogoutComponent>
//             </span>
//           </nav>
//         </div>

//         {children}
//       </body>
//     </html>
//   );
// }

"use client";

import { usePathname } from "next/navigation";
import Link from "next/link";
import { useState, useRef } from "react";
import { Toaster } from "sonner";
import { LogoutComponent } from "./components/logoutComponent";
export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  return (
    <div className="min-h-screen flex flex-col bg-slate-50/50 dark:bg-gray-950">
      {/* <Toaster position="bottom-right" richColors closeButton /> */}

      <header className="sticky top-0 z-50 w-full border-b border-slate-200/80 bg-white/80 backdrop-blur-md dark:border-gray-800/80 dark:bg-gray-900/80">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <Link href="/admin/dashboard" className="flex items-center gap-2">
            <span className="text-xl font-black bg-linear-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent tracking-tight">
              LOCAL
              <span className="text-xs font-mono font-medium tracking-normal text-slate-400">
                MART
              </span>
            </span>
          </Link>

          <nav className="hidden md:flex items-center gap-8 text-sm font-medium">
            <Link
              href="/admin/dashboard"
              className={`transition-colors duration-200 relative py-1 hover:text-blue-600 ${
                pathname === "/admin/dashboard"
                  ? "text-blue-600 font-semibold"
                  : "text-slate-600 dark:text-slate-300"
              }`}
            />

            <div className="relative" ref={dropdownRef}>
              <button
                onClick={() => setIsDropdownOpen(!isDropdownOpen)}
                className={`flex items-center gap-1 transition-colors duration-200 py-1 hover:text-blue-600 cursor-pointer active:scale-[0.98] transition-transform ${
                  isDropdownOpen || pathname.startsWith("/user/auth")
                    ? "text-blue-600 font-semibold"
                    : "text-slate-600 dark:text-slate-300"
                }`}
              >
                LOOK
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={2.5}
                  stroke="currentColor"
                  className={`w-3.5 h-3.5 transition-transform duration-200 ${isDropdownOpen ? "rotate-180" : ""}`}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="m19.5 8.25-7.5 7.5-7.5-7.5"
                  />
                </svg>
              </button>

              {isDropdownOpen && (
                <div className="absolute right-0 mt-2.5 w-48 rounded-xl border border-slate-200 bg-white p-1.5 shadow-md dark:border-gray-800 dark:bg-gray-900 animate-in fade-in zoom-in-95 duration-150 origin-top-right">
                  <>
                    <Link
                      href="/admin/category"
                      onClick={() => setIsDropdownOpen(false)}
                      className="flex w-full items-center px-3 py-2 text-xs font-semibold text-slate-700 dark:text-slate-200 rounded-lg hover:bg-slate-50 dark:hover:bg-gray-800/60 transition-colors"
                    >
                      Category
                    </Link>
                    <Link
                      href="/admin/orders"
                      onClick={() => setIsDropdownOpen(false)}
                      className="flex w-full items-center px-3 py-2 text-xs font-semibold text-slate-700 dark:text-slate-200 rounded-lg hover:bg-slate-50 dark:hover:bg-gray-800/60 transition-colors"
                    >
                      Orders
                    </Link>
                    <Link
                      href="/admin/payments"
                      onClick={() => setIsDropdownOpen(false)}
                      className="flex w-full items-center px-3 py-2 text-xs font-semibold text-slate-700 dark:text-slate-200 rounded-lg hover:bg-slate-50 dark:hover:bg-gray-800/60 transition-colors"
                    >
                      Payment
                    </Link>
                    <Link
                      href="/admin/products"
                      onClick={() => setIsDropdownOpen(false)}
                      className="flex w-full items-center px-3 py-2 text-xs font-semibold text-slate-700 dark:text-slate-200 rounded-lg hover:bg-slate-50 dark:hover:bg-gray-800/60 transition-colors"
                    >
                      Products
                    </Link>
                    {/* <Link
                      href="/user/auth/profile"
                      onClick={() => setIsDropdownOpen(false)}
                      className="flex w-full items-center px-3 py-2 text-xs font-semibold text-slate-700 dark:text-slate-200 rounded-lg hover:bg-slate-50 dark:hover:bg-gray-800/60 transition-colors"
                    >
                      My Profile
                    </Link> */}
                  </>
                </div>
              )}
            </div>
          </nav>

          <div className="flex items-center gap-4">
            <LogoutComponent></LogoutComponent>
          </div>
        </div>
      </header>

      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8 animate-in fade-in duration-300">
        {children}
      </main>
    </div>
  );
}
