// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.21.12
// source: payment.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "payment";

export interface Empty {
}

export interface CreatePaymentDto {
  orderId: number;
  userId: number;
}

export interface UpdatePaymentDto {
  id: number;
  paymentstatus: string;
  transactionId: string;
  paymentMode: string;
  razorpayPaymentId: string;
  razorpaySignature: string;
  userId: number;
  email: string;
}

export interface DeletePaymentDto {
  id: number;
  userId: number;
}

export interface GetPaymentByIdDto {
  id: number;
  userId: number;
}

export interface Payment {
  id: number;
  userId: number;
  orderId: number;
  paymentstatus: string;
  transactionId: string;
  paymentMode: string;
  amount: number;
  razorpayPaymentId: string;
  razorpaySignature: string;
}

export interface Payments {
  payments: Payment[];
}

export const PAYMENT_PACKAGE_NAME = "payment";

export interface PaymentServiceClient {
  createPayment(request: CreatePaymentDto): Observable<Payment>;

  getAllPayments(request: Empty): Observable<Payments>;

  getPaymentById(request: GetPaymentByIdDto): Observable<Payment>;

  /** rpc deletePayment(DeletePaymentDto) returns (Empty); */

  updatePayment(request: UpdatePaymentDto): Observable<Payment>;
}

export interface PaymentServiceController {
  createPayment(request: CreatePaymentDto): Promise<Payment> | Observable<Payment> | Payment;

  getAllPayments(request: Empty): Promise<Payments> | Observable<Payments> | Payments;

  getPaymentById(request: GetPaymentByIdDto): Promise<Payment> | Observable<Payment> | Payment;

  /** rpc deletePayment(DeletePaymentDto) returns (Empty); */

  updatePayment(request: UpdatePaymentDto): Promise<Payment> | Observable<Payment> | Payment;
}

export function PaymentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createPayment", "getAllPayments", "getPaymentById", "updatePayment"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAYMENT_SERVICE_NAME = "PaymentService";
