FROM node:22-alpine

WORKDIR /app

COPY catalog-service/package*.json ./

RUN npm install

COPY catalog-service .

COPY proto ./proto

# RUN npm run build

# CMD ["node","dist/src/main.js"]
CMD ["npm","run","start:dev"]