FROM node:22-alpine

WORKDIR /app

COPY payment-service/package*.json ./

RUN npm install

COPY payment-service .

COPY proto ./proto

# RUN npm run build

# CMD ["node","dist/main.js"]
CMD ["npm","run","start:dev"]