FROM node:22-alpine

WORKDIR /app

COPY review-service/package*.json ./

RUN npm install

COPY review-service .

COPY proto ./proto

# RUN npm run build
# CMD ["node","dist/main.js"]
CMD ["npm","run","start:dev"]