// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.21.12
// source: catalog.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
// import { Size } from './product-variant/enum/size.enum';
export const protobufPackage = 'catalog';

export enum Size {
  XS = 0,
  S = 1,
  M = 2,
  L = 3,
  XL = 4,
  XXL = 5,
}

export interface CreateCategoryDto {
  name: string;
  description: string;
}

export interface Category {
  id: number;
  name: string;
  description: string;
}

export interface Empty {}

export interface Categories {
  categories: Category[];
}

export interface GetCategoryByIdDto {
  id: number;
}

export interface UpdateCategoryDto {
  id: number;
  name: string;
  description: string;
  isActive: boolean;
}

export interface DeleteCategoryDto {
  id: number;
}

export interface CreateInventoryDto {
  productVariantId: number;
  stock: number;
}

export interface Inventory {
  id: number;
  stock: number;
  reservedStock: number;
  // productVariantId: number;
}

export interface Inventories {
  inventories: Inventory[];
}

export interface GetInventoryByIdDto {
  id: number;
}

export interface UpdateInventoryDto {
  id: number;
  stock: number;
  reservedStock: number;
}

export interface DeleteInventoryDto {
  id: number;
}

export interface CreateProductDto {
  name: string;
  description: string;
  brand: string;
  categoryId: number;
}

export interface Product {
  id: number;
  name: string;
  description: string;
  brand: string;
  isActive: boolean;
  // category: Category | undefined;
  // productVariants: ProductVariant[];
  // productImages: ProductImage[];
}

export interface UpdateProductDto {
  id: number;
  name: string;
  description: string;
  brand: string;
  categoryId: number;
  isActive: boolean;
}

export interface DeleteProductDto {
  id: number;
}

export interface Products {
  products: Product[];
}

export interface GetProductByIdDto {
  id: number;
}

export interface CreateProductVariantDto {
  productId: number;
  sku: string;
  size: Size;
  price: number;
  color: string;
}

export interface ProductVariant {
  id: number;
  sku: string;
  size: Size;
  price: number;
  color: string;
  isActive: boolean;
}

export interface ProductVariants {
  productVariants: ProductVariant[];
}

export interface GetProductVariantByIdDto {
  id: number;
}

export interface UpdateProductVariantDto {
  id: number;
  productId: number;
  sku: string;
  size: Size;
  price: number;
  color: string;
  isActive: boolean;
}

export interface DeleteProductVariantDto {
  id: number;
}

export interface CreateProductImageDto {
  productId: number;
  imageUrl: string;
  isPrimary: boolean;
  displayOrder: number;
}

export interface ProductImage {
  id: number;
  imageUrl: string;
  isPrimary: boolean;
  displayOrder: number;
}

export interface ProductImages {
  productImages: ProductImage[];
}

export interface GetProductImageByIdDto {
  id: number;
}

export interface UpdateProductImageDto {
  id: number;
  productId: number;
  imageUrl: string;
  isPrimary: boolean;
  displayOrder: number;
}

export interface DeleteProductImageDto {
  id: number;
}

export const CATALOG_PACKAGE_NAME = 'catalog';

export interface CatalogServiceClient {
  getAllProducts(request: Empty): Observable<Products>;

  getProductById(request: GetProductByIdDto): Observable<Product>;

  createProduct(request: CreateProductDto): Observable<Product>;

  updateProduct(request: UpdateProductDto): Observable<Product>;

  deleteProduct(request: DeleteProductDto): Observable<Empty>;

  createCategory(request: CreateCategoryDto): Observable<Category>;

  getAllCategories(request: Empty): Observable<Categories>;

  getCategoryById(request: GetCategoryByIdDto): Observable<Category>;

  updateCategory(request: UpdateCategoryDto): Observable<Category>;

  deleteCategory(request: DeleteCategoryDto): Observable<Empty>;

  createProductVariant(
    request: CreateProductVariantDto,
  ): Observable<ProductVariant>;

  getAllProductVariants(request: Empty): Observable<ProductVariants>;

  getProductVariantById(
    request: GetProductVariantByIdDto,
  ): Observable<ProductVariant>;

  updateProductVariant(
    request: UpdateProductVariantDto,
  ): Observable<ProductVariant>;

  deleteProductVariant(request: DeleteProductVariantDto): Observable<Empty>;

  createProductImage(request: CreateProductImageDto): Observable<ProductImage>;

  getAllProductImages(request: Empty): Observable<ProductImages>;

  getProductImageById(
    request: GetProductImageByIdDto,
  ): Observable<ProductImage>;

  updateProductImage(request: UpdateProductImageDto): Observable<ProductImage>;

  deleteProductImage(request: DeleteProductImageDto): Observable<Empty>;

  createInventory(request: CreateInventoryDto): Observable<Inventory>;

  getAllInventories(request: Empty): Observable<Inventories>;

  getInventoryById(request: GetInventoryByIdDto): Observable<Inventory>;

  updateInventory(request: UpdateInventoryDto): Observable<Inventory>;

  deleteInventory(request: DeleteInventoryDto): Observable<Empty>;
}

export interface CatalogServiceController {
  getAllProducts(
    request: Empty,
  ): Promise<Products> | Observable<Products> | Products;

  getProductById(
    request: GetProductByIdDto,
  ): Promise<Product> | Observable<Product> | Product;

  createProduct(
    request: CreateProductDto,
  ): Promise<Product> | Observable<Product> | Product;

  updateProduct(
    request: UpdateProductDto,
  ): Promise<Product> | Observable<Product> | Product;

  deleteProduct(
    request: DeleteProductDto,
  ): Promise<Empty> | Observable<Empty> | Empty;

  createCategory(
    request: CreateCategoryDto,
  ): Promise<Category> | Observable<Category> | Category;

  getAllCategories(
    request: Empty,
  ): Promise<Categories> | Observable<Categories> | Categories;

  getCategoryById(
    request: GetCategoryByIdDto,
  ): Promise<Category> | Observable<Category> | Category;

  updateCategory(
    request: UpdateCategoryDto,
  ): Promise<Category> | Observable<Category> | Category;

  deleteCategory(
    request: DeleteCategoryDto,
  ): Promise<Empty> | Observable<Empty> | Empty;

  createProductVariant(
    request: CreateProductVariantDto,
  ): Promise<ProductVariant> | Observable<ProductVariant> | ProductVariant;

  getAllProductVariants(
    request: Empty,
  ): Promise<ProductVariants> | Observable<ProductVariants> | ProductVariants;

  getProductVariantById(
    request: GetProductVariantByIdDto,
  ): Promise<ProductVariant> | Observable<ProductVariant> | ProductVariant;

  updateProductVariant(
    request: UpdateProductVariantDto,
  ): Promise<ProductVariant> | Observable<ProductVariant> | ProductVariant;

  deleteProductVariant(
    request: DeleteProductVariantDto,
  ): Promise<Empty> | Observable<Empty> | Empty;

  createProductImage(
    request: CreateProductImageDto,
  ): Promise<ProductImage> | Observable<ProductImage> | ProductImage;

  getAllProductImages(
    request: Empty,
  ): Promise<ProductImages> | Observable<ProductImages> | ProductImages;

  getProductImageById(
    request: GetProductImageByIdDto,
  ): Promise<ProductImage> | Observable<ProductImage> | ProductImage;

  updateProductImage(
    request: UpdateProductImageDto,
  ): Promise<ProductImage> | Observable<ProductImage> | ProductImage;

  deleteProductImage(
    request: DeleteProductImageDto,
  ): Promise<Empty> | Observable<Empty> | Empty;

  createInventory(
    request: CreateInventoryDto,
  ): Promise<Inventory> | Observable<Inventory> | Inventory;

  getAllInventories(
    request: Empty,
  ): Promise<Inventories> | Observable<Inventories> | Inventories;

  getInventoryById(
    request: GetInventoryByIdDto,
  ): Promise<Inventory> | Observable<Inventory> | Inventory;

  updateInventory(
    request: UpdateInventoryDto,
  ): Promise<Inventory> | Observable<Inventory> | Inventory;

  deleteInventory(
    request: DeleteInventoryDto,
  ): Promise<Empty> | Observable<Empty> | Empty;
}

export function CatalogServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getAllProducts',
      'getProductById',
      'createProduct',
      'updateProduct',
      'deleteProduct',
      'createCategory',
      'getAllCategories',
      'getCategoryById',
      'updateCategory',
      'deleteCategory',
      'createProductVariant',
      'getAllProductVariants',
      'getProductVariantById',
      'updateProductVariant',
      'deleteProductVariant',
      'createProductImage',
      'getAllProductImages',
      'getProductImageById',
      'updateProductImage',
      'deleteProductImage',
      'createInventory',
      'getAllInventories',
      'getInventoryById',
      'updateInventory',
      'deleteInventory',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('CatalogService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('CatalogService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const CATALOG_SERVICE_NAME = 'CatalogService';
