// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import Link from "next/link";
// import { Toaster } from "sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "E-Commerce",
//   description: "Generated by create next app",
// };

// export default function UserLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         <Toaster position="top-center" richColors></Toaster>
//         <div>
//           <nav className="flex gap-4 p-4 bg-sky-900 text-white text-xl text-shadow-xl shadow-xl font-serif font-bold ">
//             <Link href="/user/products" className=" active:text-amber-200">
//               Home
//             </Link>
//             <Link href="/user/auth/register" className=" active:text-amber-200">
//               Register
//             </Link>
//             <Link href="/user/auth/login" className=" active:text-amber-200">
//               Login
//             </Link>
//             <Link href="/user/auth/profile" className=" active:text-amber-200">
//               Profile
//             </Link>
//             <span className="absolute top-3 right-3 z-10 rounded-full bg-white/90 backdrop-blur-xs px-3.5 py-1 text-xs font-semibold uppercase tracking-wider text-gray-700 shadow-xs">
//               <Link href="/user/cart" className="">
//                 🛒
//               </Link>
//             </span>
//             <span className="absolute top-3 right-15 z-10 rounded-full bg-white/90 backdrop-blur-xs px-3.5 py-1 text-xs font-semibold uppercase tracking-wider text-gray-700 shadow-xs">
//               <Link href="/user/wishlist">♡</Link>
//             </span>
//           </nav>
//         </div>

//         {children}
//       </body>
//     </html>
//   );
// }

"use client";

import { usePathname, useRouter } from "next/navigation";
import Link from "next/link";
import { useState, useRef, useEffect } from "react";
import { Toaster, toast } from "sonner";
import { useCartStore } from "../../../lib/store/useCart";
import { useAuthGuard } from "../hooks/useAuthGuard";

export default function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const router = useRouter();
  const { isAuthenticated } = useAuthGuard();

  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  const cart = useCartStore((state: any) => state.cart) || [];

  const totalItems = cart.reduce(
    (acc: number, item: any) => acc + item.quantity,
    0,
  );

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        dropdownRef.current &&
        !dropdownRef.current.contains(event.target as Node)
      ) {
        setIsDropdownOpen(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  return (
    <div className="min-h-screen flex flex-col bg-slate-50/50 dark:bg-gray-950">
      <header className="sticky top-0 z-50 w-full border-b border-slate-200/80 bg-white/80 backdrop-blur-md dark:border-gray-800/80 dark:bg-gray-900/80">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <Link href="/user" className="flex items-center gap-2">
            <span className="text-xl font-black bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent tracking-tight">
              LOCAL
              <span className="text-xs font-mono font-medium tracking-normal text-slate-400">
                MART
              </span>
            </span>
          </Link>

          <nav className="hidden md:flex items-center gap-8 text-sm font-medium">
            <Link
              href="/user"
              className={`transition-colors duration-200 relative py-1 hover:text-blue-600 ${
                pathname === "/user"
                  ? "text-blue-600 font-semibold"
                  : "text-slate-600 dark:text-slate-300"
              }`}
            >
              Shop
              {pathname === "/user" && (
                <span className="absolute bottom-0 left-0 right-0 h-0.5 bg-blue-600 rounded-full" />
              )}
            </Link>

            <div className="relative" ref={dropdownRef}>
              <button
                onClick={() => setIsDropdownOpen(!isDropdownOpen)}
                className={`flex items-center gap-1 transition-colors duration-200 py-1 hover:text-blue-600 cursor-pointer active:scale-[0.98] transition-transform ${
                  isDropdownOpen || pathname.startsWith("/user/auth")
                    ? "text-blue-600 font-semibold"
                    : "text-slate-600 dark:text-slate-300"
                }`}
              >
                Account
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={2.5}
                  stroke="currentColor"
                  className={`w-3.5 h-3.5 transition-transform duration-200 ${isDropdownOpen ? "rotate-180" : ""}`}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="m19.5 8.25-7.5 7.5-7.5-7.5"
                  />
                </svg>
              </button>

              {isDropdownOpen && (
                <div className="absolute right-0 mt-2.5 w-48 rounded-xl border border-slate-200 bg-white p-1.5 shadow-md dark:border-gray-800 dark:bg-gray-900 animate-in fade-in zoom-in-95 duration-150 origin-top-right">
                  {isAuthenticated === false ? (
                    <>
                      <Link
                        href="/user/auth/login"
                        onClick={() => setIsDropdownOpen(false)}
                        className="flex w-full items-center px-3 py-2 text-xs font-semibold text-slate-700 dark:text-slate-200 rounded-lg hover:bg-slate-50 dark:hover:bg-gray-800/60 transition-colors"
                      >
                        Sign In
                      </Link>
                    </>
                  ) : (
                    <>
                      <Link
                        href="/user/auth/profile"
                        onClick={() => setIsDropdownOpen(false)}
                        className="flex w-full items-center px-3 py-2 text-xs font-semibold text-slate-700 dark:text-slate-200 rounded-lg hover:bg-slate-50 dark:hover:bg-gray-800/60 transition-colors"
                      >
                        My Profile
                      </Link>
                    </>
                  )}
                </div>
              )}
            </div>
          </nav>

          <div className="flex items-center gap-4">
            <Link
              href="/user/wishlist"
              className="p-2 text-slate-600 hover:text-blue-600 dark:text-slate-300 rounded-full hover:bg-slate-100 dark:hover:bg-gray-800 transition-all relative"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={2}
                stroke="currentColor"
                className="w-5 h-5"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z"
                />
              </svg>
            </Link>

            <Link
              href="/user/cart"
              className="p-2 text-slate-600 hover:text-blue-600 dark:text-slate-300 rounded-full hover:bg-slate-100 dark:hover:bg-gray-800 transition-all relative"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={2}
                stroke="currentColor"
                className="w-5 h-5"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M15.75 10.5V6a3.75 3.75 0 1 0-7.5 0v4.5m11.356-1.993 1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 0 1-1.12-1.243l1.264-12A1.125 1.125 0 0 1 5.513 7.5h12.974c.576 0 1.059.435 1.119 1.007ZM8.625 10.5a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm7.5 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z"
                />
              </svg>

              {isAuthenticated === true && totalItems > 0 && (
                <span className="absolute -top-0.5 -right-0.5 flex h-4 min-w-4 items-center justify-center rounded-full bg-blue-600 px-1 text-[10px] font-bold text-white ring-2 ring-white dark:ring-gray-900 animate-in zoom-in-50 duration-200">
                  {totalItems}
                </span>
              )}
            </Link>
          </div>
        </div>
      </header>

      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8 animate-in fade-in duration-300">
        {children}
      </main>
    </div>
  );
}
