// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.21.12
// source: order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'order';

export enum Status {
  PENDING = 0,
  CONFIRMED = 1,
  PAID = 2,
  SHIPPED = 3,
  DELIVERED = 4,
  CANCELLED = 5,
  UNRECOGNIZED = -1,
}

export interface GetMyOrderDto {
  id: number;
}

export interface Empty {}

export interface Item {
  productId: number;
  productVariantId: number;
  quantity: number;
  unitPrice: number;
  subtotal: number;
  productName: string;
  sku: string;
}

export interface CreateOrderDto {
  userId: number;
  email: string;
  items: Item[];
  shippingAddress: string;
  shippingCity: string;
  shippingState: string;
  shippingPincode: string;
  shippingPhone: string;
}

export interface GetOrderByIdDto {
  id: number;
  userId: number;
}
export interface GetOrderByIdAdminDto {
  id: number;
}

export interface Order {
  id: number;
  userId: number;
  status: Status;
  totalAmount: number;
  items: Item[];
  shippingAddress: string;
  shippingCity: string;
  shippingState: string;
  shippingPincode: string;
  shippingPhone: string;
  awbCode: string;
  courierName: string;
  shipmentId: string;
  createdAt: string;
  updatedAt: string;
}

export interface Orders {
  orders: Order[];
}

export interface UpdateOrderDto {
  id: number;
  status: Status;
}

export interface DeleteOrderDto {
  id: number;
  userId: number;
}

export const ORDER_PACKAGE_NAME = 'order';

export interface OrderServiceClient {
  createOrder(request: CreateOrderDto): Observable<Order>;

  getAllOrders(request: Empty): Observable<Orders>;

  getOrderById(request: GetOrderByIdDto): Observable<Order>;

  updateOrder(request: UpdateOrderDto): Observable<Order>;

  deleteOrder(request: DeleteOrderDto): Observable<Empty>;

  getMyOrder(request: GetMyOrderDto): Observable<Orders>;

  getOrderByIdAdmin(request: GetOrderByIdAdminDto): Observable<Order>;
}

export interface OrderServiceController {
  createOrder(
    request: CreateOrderDto,
  ): Promise<Order> | Observable<Order> | Order;

  getAllOrders(request: Empty): Promise<Orders> | Observable<Orders> | Orders;

  getOrderById(
    request: GetOrderByIdDto,
  ): Promise<Order> | Observable<Order> | Order;

  updateOrder(
    request: UpdateOrderDto,
  ): Promise<Order> | Observable<Order> | Order;

  deleteOrder(
    request: DeleteOrderDto,
  ): Promise<Empty> | Observable<Empty> | Empty;

  getMyOrder(
    request: GetMyOrderDto,
  ): Promise<Orders> | Observable<Orders> | Orders;

  getOrderByIdAdmin(
    request: GetOrderByIdAdminDto,
  ): Promise<Order> | Observable<Order>;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'createOrder',
      'getAllOrders',
      'getOrderById',
      'updateOrder',
      'deleteOrder',
      'getMyOrder',
      'getOrderByIdAdmin',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('OrderService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('OrderService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const ORDER_SERVICE_NAME = 'OrderService';
