networks:
  ecommerce-network:
    driver: bridge

services:
  auth-db:
    # 1. Changed service key to match depends_on
    image: postgres:15-alpine
    container_name: auth-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432" # 2. Crucial: Map to 5433 if catalog-db is already using 5432 on your laptop!
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  auth-service:
    # 3. Changed service key to order-service
    container_name: ecommerce-auth
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - DB_HOST=auth-db # 4. Correctly points to the service key above
    depends_on:
      - auth-db
    networks:
      - ecommerce-network
    restart: always

volumes:
  auth-db-data:
