// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.21.12
// source: review.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'review';

export interface Empty {}

export interface CreateReviewDto {
  productId: number;
  rating: number;
  comment: string;
  userId: number;
  orderId: number;
}

export interface UpdateReviewDto {
  id: number;
  rating: number;
  comment: string;
  userId: number;
}

export interface DeleteReviewDto {
  id: number;
  userId: number;
}

export interface GetReviewByIdDto {
  id: number;
}

export interface GetReviewsByProductIdDto {
  productId: number;
}

export interface Review {
  id: number;
  userId: number;
  productId: number;
  rating: number;
  comment: string;
}

export interface Reviews {
  reviews: Review[];
}

export const REVIEW_PACKAGE_NAME = 'review';

export interface ReviewServiceClient {
  createReview(request: CreateReviewDto): Observable<Review>;

  getAllReviews(request: Empty): Observable<Reviews>;

  getReviewById(request: GetReviewByIdDto): Observable<Review>;

  getReviewsByProductId(request: GetReviewsByProductIdDto): Observable<Reviews>;

  updateReview(request: UpdateReviewDto): Observable<Review>;

  deleteReview(request: DeleteReviewDto): Observable<Empty>;
}

export interface ReviewServiceController {
  createReview(
    request: CreateReviewDto,
  ): Promise<Review> | Observable<Review> | Review;

  getAllReviews(
    request: Empty,
  ): Promise<Reviews> | Observable<Reviews> | Reviews;

  getReviewById(
    request: GetReviewByIdDto,
  ): Promise<Review> | Observable<Review> | Review;

  getReviewsByProductId(
    request: GetReviewsByProductIdDto,
  ): Promise<Reviews> | Observable<Reviews> | Reviews;

  updateReview(
    request: UpdateReviewDto,
  ): Promise<Review> | Observable<Review> | Review;

  deleteReview(
    request: DeleteReviewDto,
  ): Promise<Empty> | Observable<Empty> | Empty;
}

export function ReviewServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'createReview',
      'getAllReviews',
      'getReviewById',
      'getReviewsByProductId',
      'updateReview',
      'deleteReview',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('ReviewService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('ReviewService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const REVIEW_SERVICE_NAME = 'ReviewService';
